"""The design system: one palette, one Plotly template, defined once here.

The world is **Roundel**: a light ground with generous air, a Santander-red
rail, a deep-red hero band carrying the roundel's circle-and-bar geometry, and
TfL corporate blue as the data ink. Red is the chrome and the identity; blue
does the reading work inside charts, so a red accent still means something when
it appears on a white card.

Nothing else in the app sets a colour, a font, a grid or a margin.
"""

from __future__ import annotations

from pathlib import Path

import plotly.graph_objects as go
import plotly.io as pio

#: Santander red — the brand anchor, used for the rail and the primary accent.
SANTANDER_RED = "#EC0000"
#: TfL roundel red — the in-chart accent, a shade deeper so it reads on white.
TFL_RED = "#DC241F"
#: TfL corporate blue — the data ink and the roundel's bar.
TFL_BLUE = "#10069F"

TOKENS: dict[str, str] = {
    "ground": "#F5F4F7",
    "card": "#FFFFFF",
    "rail": SANTANDER_RED,
    "rail_ink": "#FFFFFF",
    "rail_ink_soft": "#FCC9C9",
    "hero": "#B3060C",          # deeper than the rail so the two never merge
    "ink": "#1A1A2E",
    "ink_soft": "#62667A",
    "rule": "#E6E4EA",
    "accent": TFL_RED,
    "accent_soft": "#FDECEB",
    "blue": TFL_BLUE,
    "radius": "18px",
    "radius_sm": "12px",
    "shadow": "0 2px 4px rgba(26,26,46,.05), 0 8px 20px rgba(26,26,46,.05)",
    "grid": "#EEECF2",
}

FONT = "Public Sans"
FONT_URL = "Public+Sans:wght@400;500;600;700;800"
FONT_STACK = f'"{FONT}", "Helvetica Neue", Helvetica, Arial, sans-serif'

#: Categorical palette, ordered. Blue leads; red is reserved for the one series
#: that should stand out (weekends), and both carry a marker shape as well.
SERIES = [TFL_BLUE, TFL_RED, "#8E93A8", "#5A62C4", "#B45309"]
#: Cold-to-hot sequential ramp, built from the blue.
SCALE = ["#EDEEF7", "#C2C4E4", "#8E92CD", "#4A4FA8", TFL_BLUE]
#: Diverging ramp for correlations. Endpoints are deliberately light so the
#: printed number stays legible on every cell.
DIVERGING = ["#5A62C4", "#AFB4DE", "#F2F1F6", "#F4B7B4", "#E4736D"]

TEMPLATE_NAME = "cycle-demand"


def template() -> go.layout.Template:
    """The one Plotly template every figure uses."""
    if TEMPLATE_NAME in pio.templates:
        return pio.templates[TEMPLATE_NAME]

    t = TOKENS
    axis = dict(
        gridcolor=t["grid"], zeroline=False, linecolor=t["rule"],
        ticks="outside", tickcolor=t["rule"], ticklen=4,
        tickfont=dict(size=12.5, color=t["ink_soft"]),
        automargin=True,
    )
    tpl = go.layout.Template()
    tpl.layout = go.Layout(
        font=dict(family=FONT_STACK, size=13.5, color=t["ink"]),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        colorway=SERIES,
        margin=dict(l=74, r=22, t=38, b=54),
        hoverlabel=dict(bgcolor=t["ink"], bordercolor=t["ink"], align="left",
                        font=dict(family=FONT_STACK, size=12.5, color="#FFFFFF")),
        hovermode="closest",
        xaxis={**axis, "title": dict(font=dict(size=13, color=t["ink_soft"]), standoff=10)},
        yaxis={**axis, "title": dict(font=dict(size=13, color=t["ink_soft"]), standoff=14)},
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0,
                    font=dict(size=12.5, color=t["ink_soft"]),
                    title=dict(text=""), bgcolor="rgba(0,0,0,0)"),
        colorscale=dict(sequential=_ramp(SCALE), diverging=_ramp(DIVERGING)),
    )
    pio.templates[TEMPLATE_NAME] = tpl
    return tpl


def _ramp(colors: list[str]) -> list[list]:
    last = len(colors) - 1
    return [[i / last, c] for i, c in enumerate(colors)]


def css_variables() -> str:
    pairs = {f"--{k.replace('_', '-')}": v for k, v in TOKENS.items()}
    pairs["--font"] = FONT_STACK
    return " ".join(f"{k}: {v};" for k, v in pairs.items())


def write_tokens_css(path: Path | None = None) -> Path:
    """Generate assets/tokens.css from TOKENS, so the palette is defined once in
    Python and the stylesheet and the charts can never drift apart."""
    path = path or Path(__file__).parent / "assets" / "tokens.css"
    path.write_text("/* Generated by theme.write_tokens_css(). Do not edit. */\n"
                    f":root {{ {css_variables()} }}\n")
    return path


def google_fonts_href() -> str:
    return f"https://fonts.googleapis.com/css2?family={FONT_URL}&display=swap"
